### ISSUE TITLE
Hist.Usuario1: Agente, poder chequear su alta en el sistema

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/InciManager_e3a#1]
Desde InciManager se podrá chequear si el agente que envía la incidencia está dado de alta en el sistema mediante Agents

**Comment by FJss23** [comment]
Se valida que el agente que envía la incidencia este dado de alta en el sistema pero para ello se utiliza la BD que tenemos actualmente en el proyecto (donde tenemos una tabla Agentes) en el futuro será necesario acceder mediante REST al módulo Agents pero si se comparte la BD se dejaría igual.
