### ISSUE TITLE
Password de usuarios y agentes - encriptación

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/InciManager_e3a#12]
Falla recuperar un agente de la BD pq se está guardando la contraseña encriptada, y al leerla no desencripta correctamente.
En la tabla usuarios no se guardan encriptadas, hay que seguir el mismo criterio que para agentes.
Modificar para que encriptado/desencriptado sea correcto, o sino quitar de momento la función de encriptar contraseñas.

**Comment by PelayoDiaz** [comment]
ya no usable
