### ISSUE TITLE
Histo.Usuario: Agente (no sensor) poder meter incidencia via web

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/InciManager_e3a#13]
Un agente (que no sea de tipo sensor) podrá meter una incidencia al sistema via web. Logeándose identificador/contraseña (hay que controlar que: esté dado de alta como Agente, se hace simulando comunicacion con módulo Agents como hizo Fran para los sensores; y verificando que tiene permiso_envio = 'si' en TAGENTES) y rellenando los campos correspondientes a la incidencia.

**Comment by PelayoDiaz** [comment]
terminado
