### ISSUE TITLE
Definir qué incidencias se guardan

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/InciManager_e3a#20]
Según enunciado, no se guardan todas: el sistema sólo almacenará las incidencias de personas y entidades y de los sensores sólo algunos valores (podemos guardar las que se salgan de los baremos, ejm. temperaturas por encima o por debajo de los param. establecidos en la tabla de configuración del CM)

**Comment by saulcasti** [comment]
Hemos decido que solo se guardarán aquellas incidencias que se salgan de los umbrales y las creadas por agentes (personas).
