### ISSUE TITLE
Modelo de Datos

### ISSUE THREAD

**Issue by ameliafb** [Arquisoft/InciManager_e3a#8]
Amelia: preparo modelo de datos según lo comentado hoy (en mi rama). Solicitaré pull requests cuando esté listo para verificar.
@saulcasti

**Comment by ameliafb** [comment]
subido a master nueva version de modelo de datos (con tipos).

**Comment by saulcasti** [comment]
Creo que con los últimos cambios, y con el uso de la nueva bdd local esta issue la podemos cerrar
